const groups = [
	{
		id: 0,
		level: "Poziom początkujący",
		day: "Poniedziałek",
		coach: "Władysław Rorzecki",
		hour: "16:30-17:30",
		numberofclasses: 16,
		price: 800,
		start: "18 września",
		freeplaces: 8,
	},
	{
		id: 1,
		level: "Poziom początkujący+",
		day: "Poniedziałek",
		coach: "Nikodem Musik",
		hour: "16:30-17:30",
		numberofclasses: 16,
		price: 800,
		start: "18 września",
		freeplaces: 8,
	},
	{
		id: 2,
		level: "Poziom Masters",
		day: "Poniedziałek",
		coach: "Alisa Morozova",
		hour: "17:30-18:30",
		numberofclasses: 16,
		price: 800,
		start: "18 września",
		freeplaces: 10,
	},
	{
		id: 3,
		level: "Poziom zaawansowany",
		day: "Poniedziałek",
		coach: "Władysław Rorzecki",
		hour: "17:30-18:30",
		numberofclasses: 16,
		price: 800,
		start: "18 września",
		freeplaces: 10,
	},
	{
		id: 4,
		level: "Poziom zaawansowany",
		day: "Wtorek",
		coach: "Władysław Rorzecki",
		hour: "19:00-20:00",
		numberofclasses: 17,
		price: 850,
		start: "19 września",
		freeplaces: 10,
	},
	{
		id: 5,
		level: "Poziom początkujący+",
		day: "Wtorek",
		coach: "Oskar Miłoszewski",
		hour: "18:30-19:30",
		numberofclasses: 17,
		price: 850,
		start: "19 września",
		freeplaces: 8,
	},
	{
		id: 6,
		level: "Poziom Masters",
		day: "Wtorek",
		coach: "Joanna Zumska",
		hour: "20:30-21:30",
		numberofclasses: 17,
		price: 850,
		start: "19 września",
		freeplaces: 10,
	},
	{
		id: 7,
		level: "Poziom początkujący",
		day: "Środa",
		coach: "Władysław Rorzecki",
		hour: "16:30-17:30",
		numberofclasses: 18,
		price: 900,
		start: "20 września",
		freeplaces: 8,
	},
	{
		id: 8,
		level: "Poziom początkujący",
		day: "Środa",
		coach: "Nikodem Musik",
		hour: "16:30-17:30",
		numberofclasses: 18,
		price: 900,
		start: "20 września",
		freeplaces: 8,
	},
	{
		id: 9,
		level: "Poziom triathlon",
		day: "Środa",
		coach: "Oskar Miłoszewski",
		hour: "19:30-20:30",
		numberofclasses: 18,
		price: 900,
		start: "20 września",
		freeplaces: 10,
	},
	{
		id: 10,
		level: "Poziom początkujący",
		day: "Piątek",
		coach: "Nikodem Musik",
		hour: "16:30-17:30",
		numberofclasses: 16,
		price: 800,
		start: "21 września",
		freeplaces: 8,
	},
	{
		id: 11,
		level: "Poziom początkujący+",
		day: "Piątek",
		coach: "Joanna Zumska",
		hour: "16:30-17:30",
		numberofclasses: 16,
		price: 800,
		start: "21 września",
		freeplaces: 8,
	},
	{
		id: 12,
		level: "Poziom zaawansowany",
		day: "Piątek",
		coach: "Alisa Morozova",
		hour: "17:30-18:30",
		numberofclasses: 16,
		price: 800,
		start: "21 września",
		freeplaces: 8,
	},
	{
		id: 13,
		level: "Poziom masters",
		day: "Piątek",
		coach: "Oskar Miłoszewski",
		hour: "20:30-21:30",
		numberofclasses: 16,
		price: 800,
		start: "21 września",
		freeplaces: 10,
	},
	{
		id: 14,
		level: "Poziom triathlon",
		day: "Piątek",
		coach: "Nikodem Musik",
		hour: "20:30-21:30",
		numberofclasses: 16,
		price: 800,
		start: "21 września",
		freeplaces: 10,
	},
	{
		id: 15,
		level: "Poziom zaawansowany",
		day: "Sobota",
		coach: "Władysław Rorzecki",
		hour: "12:30-13:30",
		numberofclasses: 19,
		price: 950,
		start: "22 września",
		freeplaces: 10,
	},
	{
		id: 16,
		level: "Poziom zaawansowany",
		day: "Sobota",
		coach: "Nikodem Musik",
		hour: "13:30-14:30",
		numberofclasses: 19,
		price: 950,
		start: "22 września",
		freeplaces: 10,
	},
	{
		id: 17,
		level: "Poziom masters",
		day: "Sobota",
		coach: "Joanna Zumska",
		hour: "13:30-14:30",
		numberofclasses: 19,
		price: 950,
		start: "22 września",
		freeplaces: 10,
	},
	{
		id: 18,
		level: "Poziom triathlon",
		day: "Sobota",
		coach: "Alisa Morozova",
		hour: "14:30-15:30",
		numberofclasses: 19,
		price: 950,
		start: "22 września",
		freeplaces: 10,
	},
];
